import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "@/lib/providers";
import { Sidebar } from "@/components";
import { AppWrapper, PageWrapper } from "@/styles/AppStyles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppWrapper>
            <Sidebar />
            <PageWrapper>{children}</PageWrapper>
          </AppWrapper>
        </Providers>
      </body>
    </html>
  );
}
