import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "@/lib/providers";
import { Header, Sidebar } from "@/components";
import { AppWrapper, PageWrapper } from "@/styles/AppStyles";

const mulish = Mulish({ subsets: ["cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Providers>
          <AppWrapper>
            <Sidebar />
            <PageWrapper>
              <Header />
              {children}
            </PageWrapper>
          </AppWrapper>
        </Providers>
      </body>
    </html>
  );
}
